config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  # get "/home", to: "pages#home"
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
    search = params[:member]
    @team = ["Dion", "Wiebke", "Nikos", "Arbi"]

    if search.present?
      @team = @team.select { |member| member == search.capitalize }
    end
  end

  def home
    @today = Date.today.strftime("%A, %b %d")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp489</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="background: lightgray; padding: 16px">
      Nav
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is my first view!</h1>

app/views/pages/contact.html.erb
<h1>Our contact</h1>

<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?" value="<%= params[:member] %>">
  <input type="text" name="email">
  <input type="submit">
</form>

<ul>
  <% @team.each do |member| %>
    <li>
      <%= member %>
    </li>
  <% end %>
</ul>


<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>This is my homepage</h1>


<p>Today is <strong><%= @today %></strong></p>



<%= link_to "Contact", contact_path %>
<%= link_to "About", about_path %>

<% %>
<!-- er + tab -->
<%= %>
<!-- pe + tab -->